import './globals.css';
import { Inter } from 'next/font/google';
import Script from 'next/script'; // Import the Script component

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const googleAnalyticsId = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID;

  return (
    <html lang="en">
      <head>
        <title>Edson&apos;s Portfolio</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="author" href="https://edson-li.vercel.app"></link>
        <meta name="author" content="Edson Li"></meta>
        <meta name="keywords" content="Edson,Portfolio,Resume"></meta>

        {/* Google Analytics Script */}
        <Script 
          async
          id='google-analytics'
          src={`https://www.googletagmanager.com/gtag/js?id=${googleAnalyticsId}`}
        />
        <Script id='google-analytics-config'>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${googleAnalyticsId}');
          `}
        </Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}